### ISSUE TITLE
Can't install from the Chrome Web Store

### ISSUE THREAD

**Issue by jfowlie** [adeekshith/netflix-categories#1]
I get an error message:

- Package is invalid. Details: 'Default locale is defined but default data couldn't be loaded.'.

Then it bombs out of the installation attempt.

I run in en_CA for locale most of the time, I'm not sure if that's part of the problem.

**Comment by adeekshith** [comment]
Thanks for reporting it James. Not sure why that happened. I will change my locale and test it. Thanks :)

**Comment by jfowlie** [comment]
Hi--

Sorry for the very very slow response. I forgot to check back in on Github, and completely missed your very timely response.

I just pulled the netflix-categories plugin down now, got it installed with no issues whatsoever, and it works wonderfully!

Thank you for looking into this and, again, my apologies for not following up more quickly.

All the best,
--James

**Comment by adeekshith** [comment]
Thanks James!
