### ISSUE TITLE
GitHub add to chrome link is broken

### ISSUE THREAD

**Issue by dsopko** [adeekshith/netflix-categories#18]
Clicking on the add to Chrome link on this projects github homepage 

404. That’s an error.
The requested URL was not found on this server. That’s all we know.

It seems this extension does not exist on the Chrome Extension web store.

**Comment by adeekshith** [comment]
Thanks for reporting! This is fixed. It is back on Chrome web store now. It seems one of my other private extension was in violation of their updated program policies so they suspended my entire account. Delegated with them from past few weeks to just remove the faulty extension and keep others. Good news is it is finally back (although we lost lots of users). https://chrome.google.com/webstore/detail/netflix-categories/lnbopcabgddpanjmeabponnjngbmemml

I am still asked to make a few changes which are not very clear. Will work on it this week and make sure it will not be taken down again.
